### PR TITLE
Resetting size of panes after data change and fix 'window is not defined' issue

### PR DESCRIPTION
**Pull request by pprzetacznik**

### CODE REVIEW

**Comment by pprzetacznik** [comment]
https://github.com/antoniandre/splitpanes/issues/43

**Comment by jonathan-roy** [comment]
@antoniandre Would it be possible to merge this PR please?

**Comment by antoniandre** [comment]
Sorry but I can't merge the following lines break this example: https://antoniandre.github.io/splitpanes/#programmatic-resizing

```js
this.panes = this.panes.map(pane => {
    pane.savedWidth = pane.width
    return pane
})
```

I will have a look later if I can find a solution

**Comment by jonathan-roy** [comment]
Ok thank you for your feedback!

**Comment by pprzetacznik** [comment]
@antoniandre that's really bizarre because when I've created sandbox with that code and with programmatic resizing example, it just works fine.

https://codesandbox.io/s/example-splitpanes-saved-width-newd7

**Comment by antoniandre** [comment]
Hi @pprzetacznik, I don't know if it's intended but also in your codesandbox the splitpanes splitter does not move from external control, which it does in the current documentation.

Let me know if that's not supposed to happen. otherwise I'll have a look later this week.

And thanks for your contribution anyway!

**Comment by pprzetacznik** [comment]
@antoniandre you're right. Haven't checked it both ways.

**Comment by jhuss** [comment]
if the line 321 in [splitpanes.vue](https://github.com/antoniandre/splitpanes/blob/299b521c64707622a8b41edcc356579ed55be0e7/src/components/splitpanes.vue#L321) be changed to:

`if (!pane.savedWidth) pane.savedWidth = parseFloat(pane.width);`

this would be fixed?

**Comment by antoniandre** [comment]
That's right @jhuss, thanks for that. 
Now since this PR it only goes one way for the reactivity while resizing (resizing from splitter does not update values). https://antoniandre.github.io/splitpanes/#programmatic-resizing

I still don't have time to redo the whole splitpanes logic, sorry guys if I can only do some patches here and there.

**Pull request merged**
